### ISSUE TITLE
Update for ngrx 6.x and Angular 6.x

### ISSUE THREAD

**Issue by faheemhameed** [arnesson/angular-cordova#13]
Hi there,

Would you please upgrade your package for  ngrx 6.x and Angular 6.x?

Currently I am getting this error:

`ERROR in node_modules/angular-cordova/index.ts(3,10): error TS2305: Module '"httpdocs/ngapp/node_modules/rxjs/Observable"' has no exported member 'Observable'.`

Problem would be solved if you change this:

`import { Observable } from 'rxjs/Observable';
`

`import { Observable } from 'rxjs';`

Other files too have this issue.

Thanks...

**Comment by natsuki14** [comment]
What about `import 'rxjs/add/operator/share';` of index.ts?
`import { share } from 'rxjs/operators';` works in my environment.
