### ISSUE TITLE
Upgrade to pipeable operators? rxjs 5.5x

### ISSUE THREAD

**Issue by ndcunningham** [arnesson/angular-cordova#4]
https://github.com/ReactiveX/rxjs/blob/master/doc/pipeable-operators.md

**Comment by robertarnesson** [comment]
would be nice, but it would make this project not compatible with angular versions prior to 5

**Comment by ndcunningham** [comment]
That's true, maybe sometime in the future when syntax for chaining `A.map.filter` operators are dropped
